### ISSUE TITLE
NoMethodError: undefined method `info' for main:Object

### ISSUE THREAD

**Issue by slavajacobson** [sgruhier/capistrano-db-tasks#102]
$ cap --backtrace production app:pull
[Deprecation Warning] git_strategy is deprecated and will be removed in Capistrano 3.7.0.
https://github.com/capistrano/capistrano/blob/master/UPGRADING-3.7.md
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.0.0-p643
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-linux]
cap aborted!
NoMethodError: undefined method `info' for main:Object
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/bundler/gems/capistrano-db-tasks-5da36172e9c3/lib/capistrano-db-tasks/database.rb:158:in `initialize'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/bundler/gems/capistrano-db-tasks-5da36172e9c3/lib/capistrano-db-tasks/dbtasks.rb:105:in `new'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/bundler/gems/capistrano-db-tasks-5da36172e9c3/lib/capistrano-db-tasks/dbtasks.rb:105:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.3.0/lib/rake/task.rb:248:in `call'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/home/vagrant/.rvm/gems/ruby-2.0.0-p643/gems/airbrussh-1.1.1/lib/airbrussh/rake/context.rb:62:in `execute'

Rails 4
Capistrano 3.6.1
Capistrano DB Tasks - Master branch (Tried 0.5 too)

**Comment by numbata** [comment]
@slavajacobson thanks for report
