### ISSUE TITLE
If this gem is required, and `rails_env` is not specified, it defaults it to `production`. This breaks `cap staging XXX` silently..

### ISSUE THREAD

**Issue by ktaragorn** [sgruhier/capistrano-db-tasks#45]
Capistrano 3 doesnt require us to set `rails_env`, so I havent set it. However on requiring this gem, it [auto sets that to production](https://github.com/sgruhier/capistrano-db-tasks/blob/master/lib/capistrano-db-tasks/dbtasks.rb#L6). Thus deploying to staging is now broken. This is handled by setting `rails_env` as specified in the todo.. but this should just not happen.. Silently breaking capistrano even when not explicitly using the db tasks.. is evil...

Wasted a lot of time before we spotted the dark blue `RAILS_ENV=production` over the black background of the terminal..

**Comment by numbata** [comment]
Fixed with https://github.com/sgruhier/capistrano-db-tasks/commit/481ef1aea286190300c5945a152606c177cc1697. Waiting for new version of gem.

**Comment by numbata** [comment]
fixed in [v0.4](https://github.com/sgruhier/capistrano-db-tasks/tree/v0.4).
