### ISSUE TITLE
Does not play nice with DATABASE_URL env var

### ISSUE THREAD

**Issue by ktaragorn** [sgruhier/capistrano-db-tasks#46]
Active record recognizes `DATABASE_URL` env var and uses it instead of `database.yml`, however your gem doesnt. We are using the URL for RDS, setting it with dotenv, just fyi

**Comment by donbobka** [comment]
:+1:

**Comment by donbobka** [comment]
#54

**Comment by numbata** [comment]
@ktaragorn @donbobka PR #70 merged into master. It should resolve your issue. Reopen this issue if not, please.
