### ISSUE TITLE
GZip instead of BZip2

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sgruhier/capistrano-db-tasks#48]
Is there any reason why BZip2 is used without option to change compression? We use this gem heavily for larger databases and GZip would be much better option, because it compresses much faster.

**Comment by sauliusgrigaitis** [comment]
I'm not going to use BZip2 any more for db compression, so I just replaced it with GZip auliusgrigaitis/capistrano-db-tasks@f988c6514f9c7f6cbf213772db1d17402bd50ec4

**Comment by numbata** [comment]
@sauliusgrigaitis @dmitry review please.

**Comment by dmitry** [comment]
@numbata :+1: looks nice!

**Comment by sauliusgrigaitis** [comment]
:+1:
