### ISSUE TITLE
When there is a new version of gem?

### ISSUE THREAD

**Issue by numbata** [sgruhier/capistrano-db-tasks#56]
There is a lot of fixes after v0.3 version: https://github.com/sgruhier/capistrano-db-tasks/compare/v0.3...master

Some of fixes are very important for pg users.

**Comment by PanfilovDenis** [comment]
:+1:  I need it too)

**Comment by vdv73rus** [comment]
+

**Comment by sitnikovme** [comment]
Agree. Can't wait when a new gem will be released. Please do it ASAP.

**Comment by zzet** [comment]
:+1:

**Comment by PlugIN73** [comment]
:+1:

**Comment by artempartos** [comment]
yep!
Do it, please!

**Comment by zabolotnov87** [comment]
:+1:

**Comment by sgruhier** [comment]
Done 
Very sorry about the delay
If anyone want to be a collaborator on this gem, you are more than welcome :)

**Comment by numbata** [comment]
@sgruhier I want  :)

**Comment by zzet** [comment]
@sgruhier thx!

**Comment by sgruhier** [comment]
@numbata I added you as collaborator
